Cray-HPE/ims-utils

CHANGELOG.md, README.md, constraints.txt, requirements.txt
The version of Jinja2 that we use is not pinned to the version of MarkupSafe that we use.  When a newer version of MarkupSafe was released it did not follow correct semver practices and released a version that broke Jinja2.  This pins MarkupSafe to a version that works correctly with the version of Jinja2 that we want to include.
At the same time, this fixes the dev.cray.com addresses that will be retired shortly. 
* Resolves [CASMCMS-8093](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8093)
* Resolves [CASMCMS-7970](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7970)
* Build system
This will be tested in its entirety when the services that use this image are tested before they are released.
Low risk.
=> CASMCMS-8093 - update python constraint for broken dependency

CHANGELOG.md, constraints.txt
Fix the version of ims-python-helper to get the most up to date version beyond 2.9.0 so it will automatically grab newer versions.
* Resolves [CASMCMS-7970](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7970)
This will be completely tested when picked up by ims.
=> CASMCMS-7970 - fix ims-python-helper to pick up correct version.

CHANGELOG.md, scripts/fetch.py
There are times where the file download fails the first time due to intermittent network issues. This is related to CASMTRIAGE-4504. This change adds a retry loop so one http failure doesn't torpedo the entire ims job.
* Resolves [CASMCMS-8316](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8316)
* `Shandy`
This image is used by the ims service when a customize or create job is created. I uploaded the new version of the image to shandy and modified the ims configuration to use the test image for new jobs. I was then able to start new jobs with debug parameters where the fine download was performed in an infinite loop. We could see where the initial download failed and it had to try multiple times to succeed. Other times it succeeded on the first attempt.
- Were the …
=> CASMCMS-8316 - add retry to file download in fetch.py

CHANGELOG.md, scripts/fetch.py
When templates are applied to recipe files, it creates a new temporary file with the template values applied, then removes the original file, then moves the new file into the old files location. This was losing the permission flags on the original file. For shell scripts, it lost the 'execute' flag so the script was no longer able to run.
The fix is to just copy the original file permission flags to the new new file before the file switch happens.
* Resolves [CASMTRIAGE-4784](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4784)
* `beau`
I installed the new ims-utils image on beau and modified the recipe build config map to use the new image. I was able to create a new image from the original cos recipe, then run a new customize job on the resulting image. This new image had all …
=> CASMTRIAGE-4784 - preserve file permissions when applying recipe templates.

CHANGELOG.md, Dockerfile, Jenkinsfile.github, Makefile
This changes the build pipeline to produce both arm64 and x86 versions of the docker image. This is required to support the arm64 based image building.
* Resolves [CASMCMS-8368](https://github.com/Cray-HPE/ims-utils/compare/CASMCMS-8368)
* `Surtur`
I examined the produced manifest file for the image and it lists both linux/arm64 and linux/amd64 based images. I then installed the image on Surtur and ran customization jobs to insure the image works in existing x86 image jobs. The testing for the arm64 side will have to wait until we have the qemu emulator set up. …
=> CASMCMS-8368 - add arm64 support for image.

CHANGELOG.md, scripts/build_ca_rpm.py, scripts/package_and_upload.sh
In order for the arm64 recipes to successfully complete, there were a couple more tweaks needed:
1) Build and package the cert rpm as 'noarch' so it can be used for both arm64 and x86.
2) Use the correct default kernel file name depending on the arch being built.
* Resolves [CASMCMS-8365](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8365)
* `Mug`
Deployed the test image on Mug and ran a recipe build - it succeeded.
This is lower risk.
=> CASMCMS-8365 - tweaks to build arm64 recipes.

CHANGELOG.md, constraints.txt
The csm-1.3.4 release picked up some new (incompatible) changes from the latest ims-python-helper. This pins the release of ims-python-helper that should be used so each compile will not update that version. 
* Resolves [CASMINST-6450](https://jira-pro.it.hpe.com:8443/browse/CASMINST-6450)
* `Fanta`
I verified the 1.3.4 upgrade was not working correctly, then updated the version of ims-utils being used to this one, and re-tested and all works as it should.
This is a low risk change, as it just …
=> CASMINST-6450 - pin versions for csm-1.3.4 release.

CHANGELOG.md, README.md, scripts/fetch-recipe.sh, scripts/fetch.py
There is a limited amount of ephemeral storage on the k8s cluster. We were seeing cases where IMS jobs were failing due to insufficient resources. In order to resolve this, I switched the primary image and recipe mounts in the IMS jobs to use PVC's for volume mounts instead of the ephemeral storage they were using.
* Resolves [CASMCMS-8801](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8801)
* Change will also be needed in ims and ims-kiwi-builder repos.
* `Mug`
I did a helm install/upgrade/downgrade. I ran all the dkms and non/dkms recipe build and customization permutations. They all performed as expected. There is a change to the job data record (to keep track of the PVC created for the job) and I did upgrade/downgrade testing.
- Were the install/upgrade-based validation checks/tests …
=> CASMCMS-8801 - switch to using PVC for image mount.

CHANGELOG.md, Dockerfile.remote, config/sshd_config, constraints.txt, scripts/fetch.py, scripts/prep-env.sh, scripts/remote_customize_entrypoint.sh
This adds support for remote customize IMS jobs. It works in conjunction with changes in ims and ims-utils to set up, use, and tear down a remote job.
* Resolves [CASMCMS-8821](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8821)
* `Mug`
Installed the new version of ims, ims-utils, and ims-sshd and ran remote and local jobs with and without ssh jails. All work as expected.
Same risk as the rest of this project.
=> CASMCMS-8821 - Add remote build customize job options.

CHANGELOG.md, scripts/buildenv-sidecar.sh, scripts/fetch-recipe.sh, scripts/remote_customize_entrypoint.sh
Changes to automatically get the IMS ssh key and inject it into the jobs.
* Resolves [CASMCMS-8818](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8818)
* `Mug`
Update the image on Mug and run jobs to test the results.
Same risk as the rest of the remote jobs work.
=> CASMCMS-8818 - changes for ssh key injection.

CHANGELOG.md, scripts/prep-env.sh
Add options to the build of the remote image to target the correct arch of the remote node.
* Resolves [CASMCMS-8897](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8897)
* `Baldar`
Installed the new binary on the machine and set up a blanca peak node as the remote build node. This change was required to build the correct image to run on the remote build node.
Minor risk compared to the entire project.
=> CASMCMS-8897 - changes for aarch64 remote build node.

CHANGELOG.md, Dockerfile, scripts/prep-env.sh
Change the scripts to look for an unused port on the remote build node and start / connect to the remote container using that available port. This allows multiple jobs to run instead of having a single hard-coded port that is used.
* Resolves [CASMCMS-8895](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8895)
* `Tyr`
I updated the version of the images being used to the test image and ran through multiple scenarios of kicking off many remote customize jobs in rapid succession. In the logs I verified it always correctly sorted out finding an available port with no unhandled collisions.
- Was …
=> CASMCMS-8895 - allow multiple concurrent remote customize jobs.

CHANGELOG.md, scripts/remote_customize_entrypoint.sh, update_external_versions.conf
This fixes a problem with the wrong ims python helper version and adds a trap to the remote entrypoint script to help cleanup on abnormal exit.
* Resolves [CASMCMS-8923](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8923)
* `Baldar`
Installed on machine and tested abnormal shutdowns to insure remote resources got cleaned up correctly.
Low risk
=> CASMCMS-8923 - update python-helper version and add traps to bash script.

CHANGELOG.md, scripts/buildenv-sidecar.sh, scripts/remote_customize_entrypoint.sh
If the /etc/resolv.conf file that existed in the original image was a broken symbolic link, the process of saving off the original and restoring it at the end of the operation failed. Now it checked directly for a symbolic link and also moves that regardless of if the link is broken or valid.
I also discovered some issues with the complete/failed flag files so those are now straightened out as well.
* Resolves [CASMTRIAGE-6885](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-6885)
* `Tyr`
I installed the new test version of the image on Tyr and ran all combinations of remote and local x86 and aarch64 customize jobs, insuring that the resolv.conf file was correctly handled and the failed/complete flags behaved as they are supposed to.
- Were the install/upgrade-based validation …
=> CASMTRIAGE-6885 - fix etc/resolv.conf resolution for broken symlinks.

CHANGELOG.md, Dockerfile
To help future CVE issues, only install the parts of openssh that we use, not the entire package.
* Resolves [CASMCMS-9037](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-9037)
* `Wasp`
Ran through the entire range of workflows that use these scripts. Everything ran successfully with no errors in the log output.
Low risk.
=> CASMCMS-9037 - remove unused ssh features.

CHANGELOG.md, constraints.txt
On wasp, IMS image customization sessions were failing with a Python stacktrace. Investigating, it appears that some of the pinned Python modules were unhappy with the upgrade to Python 3.12 (that came along as a consequence of updating the Alpine version). This PR placates it. I tested it on wasp and confirms that it corrects the issue.
Before:
```
+ python3 -m ims_python_helper image set_job_status 9e7cd1d2-a8ba-400b-b916-d7ef542f9751 error
Traceback (most recent call last):
File "<frozen runpy>", line 189, in _run_module_as_main
Error: Downloading image return_code = 1
Warning: Could not set job status for job 9e7cd1d2-a8ba-400b-b916-d7ef542f9751 to error
File "<frozen runpy>", line 148, in _get_module_details
File "<frozen runpy>", line 112, in _get_module_details
File …
```
=> CASMTRIAGE-7899: Bump dependency versions to work with Python 3.12

CHANGELOG.md, Dockerfile
The upgraded version of alpine has changed the utilities and what options they use. I was able to upgrade a couple of the utilities, and I had to change a script in the rpmbuild install, but now building the ca-certs rpm works correctly in the recipe build path.
* Resolves [CASMTRIAGE-7899](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-7899)
* `Wasp`
I installed the new ims-utils binary and configured the create and customize jobs to use it. I then ran through building a recipe and customizing an image. I verified that all 'init' steps work correctly now. …
=> CASMTRIAGE-7899 - changes for alpine base image upgrade.

CHANGELOG.md, constraints.txt
CASMCMS-8022, CASMCMS-9455: ims-python-helper & python packages updated
- This was tested on `mug` and `surtur`
- Tested IMS image creation from recipe
- Tested IMS image customization
=> CASMCMS-8022, CASMCMS-9455: ims-python-helper & python packages updated

CHANGELOG.md, constraints.txt
CASMCMS-9510: Updated ims-python-helper version to 3.3.x
=> CASMCMS-9510: Updated ims-python-helper version to 3.3.x

CHANGELOG.md, constraints.txt
- Update `kubernetes` module to match CSM Kubernetes version
- CASMCMS-9510: Updated ims-python-helper version to 3.3.x
=> Develop->master CASMCMS-9510: Updated ims-python-helper version to 3.3.x
